Make s3_output explicit
moj-analytical-services/pydbtools pull request #130
Opened 2024-05-01 16:42 UTC by gwionap

Updating `s3_output` in `_create_temp_database`.

2024-05-09 08:07 UTC, gwionap commented
@Thomas-Hirsch - above is needed so that `_create_temp_database` uses the same s3 output location as used elsewhere and for it not to default to the workgroup's location.

Also, I think an additional environment variable is needed for grabbing the default region when used with `dbtools`. I've used `APP_AWS_REGION` for now, but open to suggestions for a better name.

2024-05-09 09:47 UTC, Thomas-Hirsch requested changes
looks ok to me. The main change I'd make is aligning with `rdbtools`'s naming convention, which uses `AWS_ATHENA_QUERY_REGION` (for what it's worth, I'm not 100% sold on that name either, but naming things is hard and it's better to be consistent). Would also be good to update the documentation to explain this and where it's applicable

2024-05-13 11:01 UTC, gwionap commented
@Thomas-Hirsch - changes made and tested ready for final review.

2024-05-13 15:37 UTC, Thomas-Hirsch approved these changes

2024-05-13 15:39 UTC, merged